apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loggen
  namespace: logging
  labels:
    k8s-app: loggen
spec:
  selector:
    matchLabels:
      name: loggen
  template:
    metadata:
      labels:
        name: loggen
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: loggen
        image: ivanovua/loggen:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
